name: cucumber_tests

dependencies:
  cucumber_wire:
    git: https://github.com/eredo/cucumber_wire.git
  webdriver: ^2.0.0
  pageloader: ^3.0.0
  yaml: ^2.1.0

dev_dependencies:
  build_runner: ^1.0.0
  source_gen: ^0.9.0